### ISSUE TITLE
Potential WebAssembly memory leak

### ISSUE THREAD

**Issue by TyLindberg** [donmccurdy/mikktspace-wasm#3]
When running the following code, the size of the WebAssembly `memory` object continues to grow with each call to `generateTangents`. I'm expecting this may be due to a memory leak in the `generateTangents` function.

```js
import { NodeIO } from "@gltf-transform/core";
import { unweld, tangents } from "@gltf-transform/functions";
import { generateTangents, __wasm } from "mikktspace";

(async () => {
  const io = new NodeIO();
  const doc = await io.read("DamagedHelmet.glb");
  await doc.transform(unweld());
  const tangentsTransform = tangents({ generateTangents });

  while (true) {
    const newDoc = doc.clone();
    await newDoc.transform(tangentsTransform);
    const wasmMem = __wasm.memory.buffer.byteLength / 1024 / 1024;
    process.stdout.write(`WASM Memory Size: ${wasmMem.toFixed(2)} MB` + "\r");
  }
})();
```

When running this code, the following error is eventually thrown.

```
(node:11169) UnhandledPromiseRejectionWarning: RangeError: offset is out of bounds
```

I'm wondering if there is a workaround to this behavior or if there is an error in the code I posted above. Let me know if I can help or provide more details.

**Comment by donmccurdy** [comment]
Thanks @TyLindberg! I've confirmed the issue — a patch is in progress at #4.

**Comment by TyLindberg** [comment]
Glad I could help! Thanks for the quick fix!
